jobs:
- job: buildmac
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        brew install ninja 
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install cmake
        python3 setup.py build
- job: buildlinux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        sudo apt -y update
        sudo apt install ninja-build -y
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user cmake
        python3 setup.py build
- job: buildWindows
  pool:
    vmImage: windows-2019
  steps:
    - script: |
        python -m pip install --upgrade pip
        python -m pip install cmake
        python setup.py build