jobs:
- job: buildmac
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        brew install ninja 
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install cmake
        python3 setup.py build
    - task: PublishBuildArtifacts@1
      displayName: upload artifacts
      inputs:
        artifactName: binaries
        pathtoPublish: build/lib.macosx-10.13-x86_64-3.7/dlib.cpython-37m-darwin.so
- job: buildlinux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
    - bash: |
        sudo apt -y update
        sudo apt install python3-setuptools -y
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user cmake
        python3 setup.py build
    - task: PublishBuildArtifacts@1
      displayName: upload artifacts
      inputs:
        artifactName: binaries
        pathtoPublish: build/lib.linux-x86_64-3.7/dlib.cpython-37m-x86_64-linux-gnu.so
- job: buildWindows
  pool:
    vmImage: windows-2019
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
    - script: |
        python -m pip install --upgrade pip
        python -m pip install cmake
        python setup.py build
    - task: PublishBuildArtifacts@1
      displayName: upload artifacts
      inputs:
        artifactName: binaries
        pathtoPublish: build\lib.win-amd64-3.7\dlib.cp37-win_amd64.pyd